mv XdbdAnyJob.cpp StatmAnyJob.cpp
mv XdbdAnyJob.h StatmAnyJob.h
mv XdbdClientDriver.cpp StatmClientDriver.cpp
mv XdbdClientDriver.h StatmClientDriver.h
mv XdbdClientHandler.cpp StatmClientHandler.cpp
mv XdbdClientHandler.h StatmClientHandler.h
mv XdbdController.cpp StatmController.cpp
mv XdbdController.h StatmController.h
mv XdbdLocalClient.cpp StatmLocalClient.cpp
mv XdbdLocalClient.h StatmLocalClient.h
mv XdbdWorker.cpp StatmWorker.cpp
mv XdbdWorker.h StatmWorker.h
mv XdbdWorkingClient.cpp StatmWorkingClient.cpp
mv XdbdWorkingClient.h StatmWorkingClient.h
